In [34]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [2]:
df = pd.read_csv("../dataset/facebook_comment_cleaned.tsv",sep='\t',encoding='utf-8')

In [7]:
scored = df[df['scoredAmt']>0]
scored['token_arr'] = scored['token'].apply(lambda x: eval(x))

/home/users/u5722780406/miniconda3/envs/tf/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [13]:
scored['score'].value_counts()
def giveClass(score):
    if(score==-32 ):
        return -32
    if(score==0):return 0
    if(score>0):return 1
    if(score<0):return -1
scored['class'] = scored['score'].apply(giveClass)

/home/users/u5722780406/miniconda3/envs/tf/lib/python3.5/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [14]:
scored['class'].value_counts()

-1     3736
-32    3270
 1     1902
 0     1850
Name: class, dtype: int64

In [205]:
def computeAcc(y,y_pred):
    print("Prediction accuracy: {}%".format(round(accuracy_score(y,y_pred)*100,2)))
    print(confusion_matrix(y,y_pred))
y = scored['class']
computeAcc(y,y_pred)

Prediction accuracy: 34.73%
[[   0 3270    0    0]
 [   0 3736    0    0]
 [   0 1850    0    0]
 [   0 1902    0    0]]


In [206]:
askwords = ['ทำไม','ยังไง','เท่าไร','ที่ไหน','ใช่ไหม','ไหน','ทำไง','ยังใง','กันแน่','มั๊ยคะ','หรือไม่','วันไหน','เท่าไหร่','เมื่อไหร่','มั้ยครับ','ตอบแชท','กี่บาท','ไหมค่ะ','บ้างค่ะ','ติดต่อ','มีไหม','สอบถาม','หรือป่าว','รึป่าว','รึเปล่า','อย่างไร','อย่างไง','ยังค่ะ','ยังคับ','ยังครับ','ถ้า','ได้ปะ','บ้างครับ','ได้ไหม','ได้ป่ะ','ได้ป้ะ','ได้ป่าว']
negwords = ['ห่วย','กาก','แย่','ปรับปรุง','ช้า','ไม่สน','อืด','ย้ายค่าย','เปลี่ยนค่าย','ควย','สัด','สาส','เหี้ย','ดกทง','ไม่ดี','กระตุก','โว้ย','หมุน']
poswords = ['แรง','เร็ว','ชื่นชม','สุดยอด','ดี','รัก','เจ๋ง','มั่นใจ','กำลังใจ','สู้ๆ','สนใจ','เริ่ด','ขอบคุณ','อยากได้','good']
def predict(message): 
    if any(word in message for word in negwords):
        return -1
    elif any(word in message for word in askwords):
        return 0
    elif any(word in message for word in poswords):
        return 1
    else:
        return -32

In [207]:
scored['pred'] = scored['message'].apply(predict)
computeAcc(y,scored['pred'])

Prediction accuracy: 50.01%
[[2434   99  338  399]
 [ 957 1795  589  395]
 [ 769  169  699  213]
 [ 596  145  709  452]]


/home/users/u5722780406/miniconda3/envs/tf/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [201]:
scored[['message','pred','class']][(scored['class']==0)&(scored['pred']==-32)].sample(20)

message  pred  class
151824                                โทรทุกค่าย ใช่ไหมคะ   -32      0
159487        มีโปร ของhuawei p 10 plus แบบนี้บ้างไหมครับ   -32      0
60881                              แอดตอบ inbox หน่อยครับ   -32      0
136022                              อ่าน in Box หน่อยครับ   -32      0
160677                P10 ที่มีโปรพิเศษกว่าข้างนอกไหมครับ   -32      0
155677  กดเว็บเเล้วก็บอกให้รีสตาร์ทเครื่อง พอทำ   เเล้...   -32      0
122444  กดรหัสอะไรครับถึงรู้ว่าใช้เบอร์นี้มากี่เดือนกี...   -32      0
130586  ผมถามคุณธนินทร์ เจียรวนนท์เรื่องข้อความสั้นกวน...   -32      0
100990  หมดวันที่6   แต่วันนี้ตัดไปแล้ว\nนร้อย.....อธิ...   -32      0
100064                       ลูกค้าเก่าอยากเปลี่ยนแพ๊คเกจ   -32      0
136023                          โปรนี้ ที่สุดแห่งความคุ้ม   -32      0
67956                            จะได้ไปดูpsi เหมื่อนเดิม   -32      0
102496                    แพ็กหลักราคาประมาณนี้มีมี้ยครับ   -32      0
17359   บางแพคเกจที่มีอินเตอร์เนตแล้ว ขอรับไม่ได้เหรอค...   -32      0
13626                                        ถูกใจสิ่งนี้   -32      0
131565  อยากรู้วิธียกเลิก package net ต่ออายุอัตโนมัติ...   -32      0
135493                   งานนี้ต้องใช้บัตรเข้าด้วยหรอครับ   -32      0
27811                 น่าจะที่อื่นแต่ไม่ใช่สามพราน นครปฐม   -32      0
99642   ไม่เห็นจริงเลย วันก่อนจะไปจ่ายค่าโทรศัพท์ ร้าน...   -32      0
123965  😣😣😣😣😤😤😤😤 ผมใช้มานานแล้ว ไม่เห้งจะมีเนตฟรีเลย อ...   -32      0